Solved task ReactivityLosing
js-tasks-ru/vue-20210810_proldapru pull request #28
Opened 2022-03-12 09:10 UTC by proldapru

Странно, несмотря на то, что реактивность была, v-for не перерисовывал компоненты SensorsDataRow (см. комментарии в коде). Изменил key -- стал перерисовывать.

2022-03-12 09:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-26 15:04 UTC, ShGKme requested changes
В 08-reactivity/01-reactivity-losing требуется ещё немного поработать с данными, чтобы решить проблемы именно через реактивность, а не ререндеринг компонента.

Вторая задача принята.

2022-04-26 15:04 UTC, ShGKme commented on 08-reactivity/01-reactivity-losing/components/SensorsDataView.vue
> +    <sensors-data-row v-for="sensor in sensors" :key="`${sensor.id}_${sensor.value}`" :sensor="sensor" />
То есть это не решает проблему "реактивности" как таковой, а решает проблему обновления страницы.

2022-04-27 06:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-04-27 06:14 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-04-27 06:14 UTC, merged